"""Tests for PROJECT_MAP.md report composition."""

from pathlib import Path

from repolens.analyzer import analyze_repository
from repolens.context_builder import RepositoryMetadata, build_context
from repolens.llm import summarize_context
from repolens.report import ReportComposer, ReportInputs, write_project_map
from repolens.scanner import RepositoryScanner


REQUIRED_SECTIONS = [
    "## Project Overview",
    "## Repository Metadata",
    "## Technology Stack",
    "## Directory / File Inventory",
    "## Important Files",
    "## Lightweight Relationships",
    "## Inferred Data Flow",
    "## Recommended Reading Order",
    "## Analysis Scope and Limitations",
    "## Generated By RepoLens",
]


def test_report_contains_all_required_sections(tmp_path: Path) -> None:
    report = _render_report(tmp_path)

    for section in REQUIRED_SECTIONS:
        assert section in report


def test_report_contains_technology_evidence_paths(tmp_path: Path) -> None:
    report = _render_report(tmp_path)

    assert "pyproject.toml" in report
    assert "requirements.txt" in report
    assert "Evidence:" in report


def test_report_contains_important_file_paths(tmp_path: Path) -> None:
    report = _render_report(tmp_path)

    assert "README.md" in report
    assert "src/app.py" in report


def test_report_contains_relationships(tmp_path: Path) -> None:
    report = _render_report(tmp_path)

    assert "src/app.py" in report
    assert "src/utils.py" in report
    assert "imports" in report


def test_report_contains_limitations_and_disclaimer(tmp_path: Path) -> None:
    inputs = _build_inputs(tmp_path)
    inputs.scan_result.limitations.append("fixture limitation")
    report = ReportComposer().compose(inputs)

    assert "fixture limitation" in report
    assert "AI-generated summaries may be inaccurate" in report
    assert "not a runtime trace" in report
    assert "Repository code was not executed" in report


def test_report_write_creates_project_map(tmp_path: Path) -> None:
    inputs = _build_inputs(tmp_path)
    output_path = tmp_path / "PROJECT_MAP.md"

    result_path = write_project_map(
        repository=inputs.repository,
        scan_result=inputs.scan_result,
        analysis_result=inputs.analysis_result,
        context_result=inputs.context_result,
        summary_result=inputs.summary_result,
        output_path=output_path,
    )

    assert result_path == output_path.resolve()
    assert output_path.exists()
    assert "## Project Overview" in output_path.read_text(encoding="utf-8")


def test_report_output_path_option_target_can_be_custom(tmp_path: Path) -> None:
    inputs = _build_inputs(tmp_path)
    output_path = tmp_path / "reports" / "CUSTOM_PROJECT_MAP.md"

    result_path = write_project_map(
        repository=inputs.repository,
        scan_result=inputs.scan_result,
        analysis_result=inputs.analysis_result,
        context_result=inputs.context_result,
        summary_result=inputs.summary_result,
        output_path=output_path,
    )

    assert result_path == output_path.resolve()
    assert output_path.exists()


def test_report_generation_is_deterministic(tmp_path: Path) -> None:
    inputs = _build_inputs(tmp_path)

    first = ReportComposer().compose(inputs)
    second = ReportComposer().compose(inputs)

    assert first == second


def _render_report(tmp_path: Path) -> str:
    return ReportComposer().compose(_build_inputs(tmp_path))


def _build_inputs(tmp_path: Path) -> ReportInputs:
    (tmp_path / "README.md").write_text("# Demo\n", encoding="utf-8")
    (tmp_path / "pyproject.toml").write_text(
        "[project]\ndependencies = ['flask']\n",
        encoding="utf-8",
    )
    (tmp_path / "requirements.txt").write_text("pytest\n", encoding="utf-8")
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "app.py").write_text("import src.utils\n", encoding="utf-8")
    (tmp_path / "src" / "utils.py").write_text("VALUE = 1\n", encoding="utf-8")
    (tmp_path / ".env").write_text("SECRET=not-in-report\n", encoding="utf-8")

    repository = RepositoryMetadata(
        owner="example",
        repo="demo",
        clone_url="https://github.com/example/demo.git",
        commit_sha="abc123",
    )
    scan_result = RepositoryScanner().scan(tmp_path)
    analysis_result = analyze_repository(scan_result)
    context_result = build_context(repository, scan_result, analysis_result)
    summary_result = summarize_context(context_result)
    return ReportInputs(
        repository=repository,
        scan_result=scan_result,
        analysis_result=analysis_result,
        context_result=context_result,
        summary_result=summary_result,
    )
